[package]
name = "test-tokenizers-codelldb-debugging-issue"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "test-issue"
path = "src/main.rs"

[dependencies]
clap = { version = "4.5.48", features = ["derive"] }
tokenizers = "0.22.1"
